# Generated by Django 5.1 on 2024-09-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Dong_vat',
        ),
        migrations.RenameModel(
            old_name='Dish',
            new_name='Mon_Che_Bien',
        ),
        migrations.RenameModel(
            old_name='AnimalCategory',
            new_name='Nhom_Dong_vat',
        ),
    ]
