# Generated by Django 5.1 on 2024-09-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dong_vat_options_alter_mon_che_bien_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dong_vat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mon_che_bien',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nhom_dong_vat',
            options={},
        ),
        migrations.RemoveField(
            model_name='mon_che_bien',
            name='price',
        ),
    ]
