# Generated by Django 5.1 on 2024-09-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_mon_che_bien_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dong_vat',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dong_vat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhom_dong_vat',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
