# Generated by Django 5.1 on 2024-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuyen_Dung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congvieccantuyen', models.CharField(max_length=100)),
                ('yeucaucongviec', models.CharField(max_length=500)),
                ('quyenloi', models.CharField(max_length=500)),
            ],
        ),
    ]
