# Generated by Django 5.1 on 2024-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuyen_dung',
            old_name='congvieccantuyen',
            new_name='cong_viec_can_tuyen',
        ),
        migrations.RemoveField(
            model_name='tuyen_dung',
            name='quyenloi',
        ),
        migrations.RemoveField(
            model_name='tuyen_dung',
            name='yeucaucongviec',
        ),
        migrations.AddField(
            model_name='tuyen_dung',
            name='mo_ta_cong_viec',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuyen_dung',
            name='quyen_loi',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuyen_dung',
            name='yeu_cau_cong_viec',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
